### ISSUE TITLE
How to download full dataset?

### ISSUE THREAD

**Issue by anilesec** [NVlabs/HANDAL#1]
Dear Authors,

I read the paper, the dataset looks pretty resourceful. I want to use it for my research.
Could you please let me know how to download it?

Thanks in Advance!

Best
Anil

**Comment by swtyree** [comment]
Hi @anilesec! We expect to release the dataset in the next couple weeks.

**Comment by SiyuanHuang95** [comment]
Hi, any update? @swtyree

**Comment by anilesec** [comment]
Yup, I am eagerly waiting for this dataset and code @swtyree 

Thank you in Advance!

**Comment by sbirchfield** [comment]
Dataset is uploading...

Let us know if you have any issues

**Comment by swtyree** [comment]
The full dataset is available, so I'm closing this issue. Feel free to open a new issue if you have any problems or questions when trying to use it. Thanks!
