### ISSUE TITLE
missing json file

### ISSUE THREAD

**Issue by EladUnlimited** [NVlabs/HANDAL#10]
Hi 
i am running the example show in the readme (bash run.sh example/drill_reference ) but from some reason during the "Generating camera poses via COLMAP" step i getting an error about a missing transforms_scene.json file.
Thank you

 
<img width="483" alt="Screenshot 2024-05-27 161630" src="https://github.com/NVlabs/HANDAL/assets/169071561/524c58f7-aa9f-4428-9e9e-d7b84f95aeb4">

edit:
it seems like the colmap2nerf.py is not running.
![image](https://github.com/NVlabs/HANDAL/assets/169071561/76cf9e85-04cb-4c76-8c43-3b397902f4fe)

**Comment by andrewyguo** [comment]
@EladUnlimited , I believe this error is happening because you are running the script inside example/drill_reference. Please run the script from the root of the HANDAL directory
