### ISSUE TITLE
Train Scripts

### ISSUE THREAD

**Issue by houph4** [NVlabs/HANDAL#11]
Hello, thank you for your team's amazing work. I would like to inquire if there are any relevant HANDAL training script references available

**Comment by andrewyguo** [comment]
hi @niu17 

The training code we used was a modified version of the official CenterPose repo:

https://github.com/NVlabs/CenterPose

However, the modified training scripts we have are very messy and we do not plan on releasing them. The dataset is released in BOP format so I suggest you try to find training scripts that run on BOP data or code to convert from BOP format to your desired training format. 

Thanks
