### ISSUE TITLE
performance 

### ISSUE THREAD

**Issue by EladUnlimited** [NVlabs/HANDAL#12]
hi all
I like to ask two questions please:
**edit: I have found a mistake with my calculation so question 1 is not relevant** 
1. i did use the demo in the git and it works pretty good (as shown in fig 
    1). in the other hand, when i use costume data the results are not 
     very accurate (as shown in fig 1 & 2). do you have any idiea how to 
      improve it  or a general guidence to how to perform the prosses for   
      a better results?
      note: the resolution for the costume data is 428x850 (the original  
      drill video is 1920x1080)
2) i did use Cutie as recommended. for the 428x850 resolution it 
     works very good but for the original resolution (1920x1080) Cutie is 
     not able to propagate the segmentation over to the following 
     frames. i have tried the original drill video as well but Cutie didn't make it 
     to propagate. can you please share how did you labeled the original 
     video?  

fig 1 -
![test](https://github.com/NVlabs/HANDAL/assets/169071561/8cc450db-0772-4df1-95a9-0d4ee9b17e24)

fig 2- 
![test2](https://github.com/NVlabs/HANDAL/assets/169071561/7f6626f8-69c2-47e8-ad9e-b85f5e8b7fb2)

fig 3 - 
![test3](https://github.com/NVlabs/HANDAL/assets/169071561/ced3d6a4-6a11-4c17-8cda-cb536f972a27)

**Comment by andrewyguo** [comment]
Hello @EladUnlimited, 

Could you elaborate on your issue with Cutie? Are you finding that the masks are not propagating when you run at higher resolutions? 

For our purposes, we found that masks that were 960x540 were enough to cleanly segment the object. This will run faster since it is processing only 1/4 of the pixels compared to 1920x1080. 

Do you need masks at 1920x1080 for a specific purpose?

**Comment by EladUnlimited** [comment]
> Hello @EladUnlimited,
> 
> Could you elaborate on your issue with Cutie? Are you finding that the masks are not propagating when you run at higher resolutions?
> 
> For our purposes, we found that masks that were 960x540 were enough to cleanly segment the object. This will run faster since it is processing only 1/4 of the pixels compared to 1920x1080.
> 
> Do you need masks at 1920x1080 for a specific purpose?

Hi
Regarding your firs question, yes. When I am using the 1920x1080 videos the masks are not propagating.

I don't specifically need to have 1920x1080, just tried to replicate your work to see if I having some problems with the process or is it just the videos that are too large. I find that any way I can't propagate the masks on the original videos.
 
So in the example you are providing is videos being use are the original one after resize for 960x540? my question (with more details) is, did you just resize the videos for the purpose of the segmentation with Cutie (and than running on your project with the original 1920x1080 resolution and the masks resize again to 1920x1080) or is the entire process (Cutie and HANDAL) is using the 960x540 resolution?

Thank you!

**Comment by andrewyguo** [comment]
Hi @EladUnlimited , sorry for late reply. 

When we run Cutie or XMem for segmentation, we don't run it at the original resolution. We usually downsample it by a factor of 2 or 3. We find that this is more computationally efficient and has similar results when we then upsample the segmentation masks for further processing. Hope this helps!
