### ISSUE TITLE
Release textured meshes

### ISSUE THREAD

**Issue by FlorisE** [NVlabs/HANDAL#13]
Thanks for the interesting work.

It seems like the released dataset only contains untextured meshes, whereas the pipeline does create textured meshes.

Could you release the textured meshes?

Pardon me if the textured meshes have already been released somewhere and I overlooked it :)

**Comment by andrewyguo** [comment]
hi @FlorisE , 

we have high quality meshes for a subset of the objects. You can find them here: https://bop.felk.cvut.cz/datasets/#HANDAL

We did not release the meshes for all of the objects because we found that the NGP reconstruction was quite poor.

**Comment by FlorisE** [comment]
Thanks, these meshes look amazing and seem great for ground truth evaluation.

I agree that NGP meshes are poor, I struggled a lot to get better-quality meshes out of NeRF... NeuS2 tends to have better geometry, but textures are still inadequate. I was surprised that the TSDF meshes generated by HANDAL were quite good.

**Comment by andrewyguo** [comment]
@FlorisE , I forgot to mention, the meshes linked above were not generated by the HANDAL pipeline. They were made manually over the course of a few months.
