### ISSUE TITLE
Whether this dataset can be used for NCOS-based method?

### ISSUE THREAD

**Issue by ziqin-h** [NVlabs/HANDAL#2]
Dear Authors,
This dataset is a great one in the field of category-level pose estimation. And I would like to know that would you provide a version containing NOCS map so researchers can try the NOCS-based method on it?
Best
Ziggy

**Comment by swtyree** [comment]
Hi @hzqtitanium, thanks for reaching out. We haven't discussed creating NOCS maps, but we'd be happy to have further discussions. Within each category, the reference mesh for each instance should be in a canonical position+rotation for that category, which should make it straightforward to normalize. Are you aware of any scripts for rendering the NOCS map for a given GT mesh + pose? I found a few relevant posts on the NOCS repo, including [this one](https://github.com/hughw19/NOCS_CVPR2019/issues/18#issue-556635373), but I likely won't have time to try to code at the moment.

**Comment by taeyeopl** [comment]
Does the same category align with canonical rotation (e.g., mug1 and mug2 have the same rotation in handle parts)?
Or does each instance have a unique rotation, regardless of the category relation?

**Comment by swtyree** [comment]
The objects should be well aligned. There are three basic object shapes: cuboids, cylinders, and "bottles" (e.g. ketchup). They are all aligned per [BOP conventions](https://github.com/thodan/bop_toolkit/blob/master/docs/bop_datasets_format.md#coordinate-systems) with top in the +Z direction and the front face in the +X direction. The selection of the front face is sometimes a judgement call, and there are often front/back symmetries. But the objects are all geometrically aligned by type, with one exception.

That exception is for the cylindrical objects. BOP sets the origin as the center of the bounding cuboid. But with all the cylindrical toy cans, there is a small tab that projects past the edge of the lid. Unfortunately this was not consistently placed during scanning or capture. In the original version of the dataset, I ignored the tab and placed the object origin at the center of the cylindrical part. But for the BOP version, I applied the origin from the BOP documentation. Correcting for this should be as simple as shifting the origin laterally by a few mm to align with the center of the cylinder.

**Comment by swtyree** [comment]
(Apologies for a first version of this reply that was geared toward the HOPE dataset instead of HANDAL. I had just checked some issues on that repo and forgot which repo I was on. 😑) The objects should be reasonably well aligned by category in HANDAL. The alignment was done by hand and we didn't have big discussions about it. But the intention was they they should be aligned logically by category.

**Comment by taeyeopl** [comment]
Thanks for the quick replies 😄
