### ISSUE TITLE
When the code might be open sourced?

### ISSUE THREAD

**Issue by Lniper** [NVlabs/HANDAL#3]
Hello！ I hope this message finds you well. I recently came across your paper "HANDAL" and found the proposed approach and results very interesting. The work shows a lot of promise to help advance research in this area. I was hoping to learn more about how the method was implemented. However, I noticed the code has not been released publicly yet. I wanted to check respectfully if you have an estimate for when the code might be open sourced? I understand the process of cleaning and documenting code takes time. Releasing it would really help the community to further test and develop this work. Thank you for considering.

**Comment by swtyree** [comment]
Hi @Lniper, we just pushed the code for the HANDAL pipeline to this repo. If you're able to give it a try, please let us know if you have any feedback or run into any problems. Thanks!

**Comment by Lniper** [comment]
Thank you for releasing the source code. I am very interested in this direction.&nbsp;I hope there will be an opportunity for collaboration in the future.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NVlabs/HANDAL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月28日(星期天) 中午12:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NVlabs/HANDAL] When the code might be open sourced? (Issue #3)





 
Hi @Lniper, we just pushed the code for the HANDAL pipeline to this repo. If you're able to give it a try, please let us know if you have any feedback or run into any problems. Thanks!
