### ISSUE TITLE
CMake Error at CMakeLists.txt:42 (message)

### ISSUE THREAD

**Issue by Lniper** [NVlabs/HANDAL#5]
Hello，
There is a problem when installing the Instant-NGP. When I execute the following cmake command, I get an error message.

Cmake command： cmake . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo
Error message：
CMake Error at CMakeLists.txt:42 (message):
      Some instant-ngp dependencies are missing.  If you forgot the "--recursive"
      flag when cloning this project, this can be fixed by calling "git submodule
      update --init --recursive".

How can I solve this issue? Thank you for your attention to the issue, and I look forward to your reply.

**Comment by swtyree** [comment]
Hi @Lniper, did you use the `--recursive` flag when cloning Instant NGP? I see that is mentioned in the error message.

Also, did you follow the suggested commands from the HANDAL [readme](https://github.com/NVlabs/HANDAL?tab=readme-ov-file#installing-instant-ngp)? If so, it could be that those don't work universally or are outdated, in which case you should follow the NGP readme directly, and perhaps we should remove those commands from our readme.

NGP can be a bit sticky to install, as I recall. Let me know where things stand, and I'll see if I can remember anything useful.

**Comment by Lniper** [comment]
Thank you very much. I have sovled this problem. It' my fault over the error on installing the suggested commands. Now, the project is progressing smoothly.&nbsp; If i have any questions, i will email u as soon as possible. Thanks again!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NVlabs/HANDAL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月2日(星期五) 凌晨2:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NVlabs/HANDAL] CMake Error at CMakeLists.txt:42 (message) (Issue #5)





 
Hi @Lniper, did you use the --recursive flag when cloning Instant NGP? I see that is mentioned in the error message.
 
Also, did you follow the suggested commands from the HANDAL readme? If so, it could be that those don't work universally or are outdated, in which case you should follow the NGP readme directly, and perhaps we should remove those commands from our readme.
 
NGP can be a bit sticky to install, as I recall. Let me know where things stand, and I'll see if I can remember anything useful.
