### ISSUE TITLE
Not enough GPU memory to match 6827 features

### ISSUE THREAD

**Issue by Lniper** [NVlabs/HANDAL#7]
Hi, i met a problem when generating camera poses via COLMAP: Not enough GPU memory to match 6827 features. Reduce the maximum number of matches. Would u please tell me where to fix this problem in configs?  Thank you in advance!

**Comment by swtyree** [comment]
I've not encountered that error before. Perhaps it's a result of the number of images or the image size? My testing was done with ~100 images at 1440x1920 resolution using a GeForce RTX 3090 GPU. How does your setup compare to those settings?
