### ISSUE TITLE
RuntimeError: Can't set fp params because buffer has the wrong size.

### ISSUE THREAD

**Issue by lpy523** [NVlabs/HANDAL#8]
I am getting the following error while trying to use the toolkit following the instructions from this repository, does anyone know how to fix it? Does this mean I'm out of CUDA memory? 
<img width="957" alt="bug" src="https://github.com/NVlabs/HANDAL/assets/138582771/a2e160bd-2f8c-491f-8d08-382f4fb021ca">

**Comment by andrewyguo** [comment]
@lpy523 it looks like this might be related to this issue: 

https://github.com/NVlabs/instant-ngp/issues/501

https://github.com/NVlabs/instant-ngp/discussions/502

**Comment by lpy523** [comment]
Thanks a lot for the reply, I'm currently trying to fix it.
I would also like to know if you could provide the source code for the experimental part of this paper? Thank you!

**Comment by lpy523** [comment]
Thanks a lot for the reply, I'm currently trying to fix it.
@andrewyguo And I was wondering if you could provide the source code for the experimental part of this paper? That will be very helpful. Thank you so much!

**Comment by andrewyguo** [comment]
Hi @lpy523, for the experiments, we used [CenterPose](https://github.com/NVlabs/CenterPose). We modified the public codebase as highlighted in the paper. I'm not sure if I am allowed to share the modified code since it has not been vetted by Nvidia and is internal code. Since I'm not an intern there anymore, I won't be able to ask to see if it can be shared.

**Comment by lpy523** [comment]
@andrewyguo Thanks for your reply! And i have another question about the dataset. How do you get _scene_gt.json_?

**Comment by andrewyguo** [comment]
@lpy523, for scene_gt.json, please see: https://github.com/NVlabs/HANDAL/blob/main/scripts/generate_gt_bop.py#L55
